with-expecter: true
disable-version-string: true
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: False
issue-845-fix: True

packages:
  github.com/andredubov/rocket-factory/payment/internal/api/v1/payment:
    config:
      include-regex: "PaymentService"
  github.com/andredubov/rocket-factory/inventory/internal/api/v1/inventory:
    config:
      include-regex: "InventoryService"
  github.com/andredubov/rocket-factory/inventory/internal/service:
    config:
      include-regex: "InventoryRepository"
  github.com/andredubov/rocket-factory/inventory/internal/repository/part/mongo:
    config:
      include-regex: "MongoCollection|MongoCursor"
  github.com/andredubov/rocket-factory/order/internal/api/v1/order:
    config:
      include-regex: "OrdersService"
  github.com/andredubov/rocket-factory/order/internal/service:
    config:
      include-regex: "OrdersRepository|InventoryClient|PaymentClient|ProducerService|ConsumerService"
  github.com/andredubov/rocket-factory/platform/pkg/kafka:
    config:
      include-regex: "Producer|Consumer"
  github.com/andredubov/rocket-factory/platform/pkg/kafka/producer:
    config:
      include-regex: "Logger"
  github.com/andredubov/rocket-factory/order/internal/converter/kafka:
    config:
      include-regex: "OrderAssembledEventDecoder"
  github.com/andredubov/rocket-factory/assembly/internal/service:
    config:
      include-regex: "ProducerService|ConsumerService"
  github.com/andredubov/rocket-factory/assembly/internal/converter/kafka:
    config:
      include-regex: "OrderPaidEventDecoder"
  github.com/andredubov/rocket-factory/assembly/internal/config:
    config:
      include-regex: "LoggerConfig|KafkaConfig|OrderAssembledProducerConfig|OrderPaidEventConsumerConfig"