with-expecter: true
disable-version-string: true
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: False
issue-845-fix: True

packages:
  github.com/andredubov/rocket-factory/payment/internal/service:
    config:
      include-regex: ".*Payment"