// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/andredubov/rocket-factory/payment/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// PaymentService is an autogenerated mock type for the PaymentService type
type PaymentService struct {
	mock.Mock
}

type PaymentService_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentService) EXPECT() *PaymentService_Expecter {
	return &PaymentService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, payment
func (_m *PaymentService) Create(ctx context.Context, payment model.Payment) (string, error) {
	ret := _m.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Payment) (string, error)); ok {
		return rf(ctx, payment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Payment) string); ok {
		r0 = rf(ctx, payment)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Payment) error); ok {
		r1 = rf(ctx, payment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PaymentService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type PaymentService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - payment model.Payment
func (_e *PaymentService_Expecter) Create(ctx interface{}, payment interface{}) *PaymentService_Create_Call {
	return &PaymentService_Create_Call{Call: _e.mock.On("Create", ctx, payment)}
}

func (_c *PaymentService_Create_Call) Run(run func(ctx context.Context, payment model.Payment)) *PaymentService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Payment))
	})
	return _c
}

func (_c *PaymentService_Create_Call) Return(_a0 string, _a1 error) *PaymentService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PaymentService_Create_Call) RunAndReturn(run func(context.Context, model.Payment) (string, error)) *PaymentService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewPaymentService creates a new instance of PaymentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentService {
	mock := &PaymentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
