// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "github.com/andredubov/rocket-factory/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// OrderAssembledEventDecoder is an autogenerated mock type for the OrderAssembledEventDecoder type
type OrderAssembledEventDecoder struct {
	mock.Mock
}

type OrderAssembledEventDecoder_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderAssembledEventDecoder) EXPECT() *OrderAssembledEventDecoder_Expecter {
	return &OrderAssembledEventDecoder_Expecter{mock: &_m.Mock}
}

// Decode provides a mock function with given fields: data
func (_m *OrderAssembledEventDecoder) Decode(data []byte) (model.OrderAssembledEvent, error) {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 model.OrderAssembledEvent
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (model.OrderAssembledEvent, error)); ok {
		return rf(data)
	}
	if rf, ok := ret.Get(0).(func([]byte) model.OrderAssembledEvent); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Get(0).(model.OrderAssembledEvent)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderAssembledEventDecoder_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type OrderAssembledEventDecoder_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - data []byte
func (_e *OrderAssembledEventDecoder_Expecter) Decode(data interface{}) *OrderAssembledEventDecoder_Decode_Call {
	return &OrderAssembledEventDecoder_Decode_Call{Call: _e.mock.On("Decode", data)}
}

func (_c *OrderAssembledEventDecoder_Decode_Call) Run(run func(data []byte)) *OrderAssembledEventDecoder_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *OrderAssembledEventDecoder_Decode_Call) Return(_a0 model.OrderAssembledEvent, _a1 error) *OrderAssembledEventDecoder_Decode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderAssembledEventDecoder_Decode_Call) RunAndReturn(run func([]byte) (model.OrderAssembledEvent, error)) *OrderAssembledEventDecoder_Decode_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderAssembledEventDecoder creates a new instance of OrderAssembledEventDecoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderAssembledEventDecoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderAssembledEventDecoder {
	mock := &OrderAssembledEventDecoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
