openapi: 3.0.3

info:
  title: Order Management API
  description: |
    API для управления заказами деталей.
    Позволяет:
    - Создавать новые заказы
    - Оплачивать заказы
    - Получать информацию о заказах
    - Отменять заказы
  version: 1.0.0

x-ogen:
  target: ./shared/pkg/openapi/order/v1
  package: order_v1
  clean: true

# Серверы API (можно добавить несколько окружений)
servers:
  - url: /api/v1
    description: Основной сервер API

# Определение всех путей (endpoints) API
paths:
  # Эндпоинт для создания заказа
  /orders:
    $ref: ./paths/orders.yaml

  # Эндпоинт для получения информации о заказе
  /orders/{order_uuid}:
    $ref: ./paths/order_by_uuid.yaml

  # Эндпоинт для оплаты заказа
  /orders/{order_uuid}/pay:
    $ref: ./paths/order_pay.yaml

  # Эндпоинт для отмены заказа
  /orders/{order_uuid}/cancel:
    $ref: ./paths/order_cancel.yaml
