// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/andredubov/rocket-factory/order/internal/model"

	uuid "github.com/google/uuid"
)

// OrdersService is an autogenerated mock type for the OrdersService type
type OrdersService struct {
	mock.Mock
}

type OrdersService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrdersService) EXPECT() *OrdersService_Expecter {
	return &OrdersService_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function with given fields: ctx, _a1
func (_m *OrdersService) CancelOrder(ctx context.Context, _a1 uuid.UUID) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrdersService_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type OrdersService_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 uuid.UUID
func (_e *OrdersService_Expecter) CancelOrder(ctx interface{}, _a1 interface{}) *OrdersService_CancelOrder_Call {
	return &OrdersService_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, _a1)}
}

func (_c *OrdersService_CancelOrder_Call) Run(run func(ctx context.Context, _a1 uuid.UUID)) *OrdersService_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *OrdersService_CancelOrder_Call) Return(_a0 error) *OrdersService_CancelOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrdersService_CancelOrder_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *OrdersService_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function with given fields: ctx, order
func (_m *OrdersService) CreateOrder(ctx context.Context, order model.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrdersService_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrdersService_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.Order
func (_e *OrdersService_Expecter) CreateOrder(ctx interface{}, order interface{}) *OrdersService_CreateOrder_Call {
	return &OrdersService_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, order)}
}

func (_c *OrdersService_CreateOrder_Call) Run(run func(ctx context.Context, order model.Order)) *OrdersService_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Order))
	})
	return _c
}

func (_c *OrdersService_CreateOrder_Call) Return(_a0 error) *OrdersService_CreateOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrdersService_CreateOrder_Call) RunAndReturn(run func(context.Context, model.Order) error) *OrdersService_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: ctx, _a1
func (_m *OrdersService) GetOrder(ctx context.Context, _a1 uuid.UUID) (*model.Order, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Order, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Order); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrdersService_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type OrdersService_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 uuid.UUID
func (_e *OrdersService_Expecter) GetOrder(ctx interface{}, _a1 interface{}) *OrdersService_GetOrder_Call {
	return &OrdersService_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, _a1)}
}

func (_c *OrdersService_GetOrder_Call) Run(run func(ctx context.Context, _a1 uuid.UUID)) *OrdersService_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *OrdersService_GetOrder_Call) Return(_a0 *model.Order, _a1 error) *OrdersService_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrdersService_GetOrder_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Order, error)) *OrdersService_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// PayOrder provides a mock function with given fields: ctx, _a1, paymentMethod
func (_m *OrdersService) PayOrder(ctx context.Context, _a1 uuid.UUID, paymentMethod string) (*model.Order, error) {
	ret := _m.Called(ctx, _a1, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*model.Order, error)); ok {
		return rf(ctx, _a1, paymentMethod)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *model.Order); ok {
		r0 = rf(ctx, _a1, paymentMethod)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, _a1, paymentMethod)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrdersService_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type OrdersService_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 uuid.UUID
//   - paymentMethod string
func (_e *OrdersService_Expecter) PayOrder(ctx interface{}, _a1 interface{}, paymentMethod interface{}) *OrdersService_PayOrder_Call {
	return &OrdersService_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, _a1, paymentMethod)}
}

func (_c *OrdersService_PayOrder_Call) Run(run func(ctx context.Context, _a1 uuid.UUID, paymentMethod string)) *OrdersService_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *OrdersService_PayOrder_Call) Return(_a0 *model.Order, _a1 error) *OrdersService_PayOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrdersService_PayOrder_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (*model.Order, error)) *OrdersService_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrdersService creates a new instance of OrdersService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrdersService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrdersService {
	mock := &OrdersService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
