// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/andredubov/rocket-factory/order/internal/model"

	uuid "github.com/google/uuid"
)

// OrdersService is an autogenerated mock type for the OrdersService type
type OrdersService struct {
	mock.Mock
}

type OrdersService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrdersService) EXPECT() *OrdersService_Expecter {
	return &OrdersService_Expecter{mock: &_m.Mock}
}

// AddOrder provides a mock function with given fields: ctx, order
func (_m *OrdersService) AddOrder(ctx context.Context, order model.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for AddOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrdersService_AddOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddOrder'
type OrdersService_AddOrder_Call struct {
	*mock.Call
}

// AddOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.Order
func (_e *OrdersService_Expecter) AddOrder(ctx interface{}, order interface{}) *OrdersService_AddOrder_Call {
	return &OrdersService_AddOrder_Call{Call: _e.mock.On("AddOrder", ctx, order)}
}

func (_c *OrdersService_AddOrder_Call) Run(run func(ctx context.Context, order model.Order)) *OrdersService_AddOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Order))
	})
	return _c
}

func (_c *OrdersService_AddOrder_Call) Return(_a0 error) *OrdersService_AddOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrdersService_AddOrder_Call) RunAndReturn(run func(context.Context, model.Order) error) *OrdersService_AddOrder_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrder provides a mock function with given fields: ctx, _a1
func (_m *OrdersService) DeleteOrder(ctx context.Context, _a1 uuid.UUID) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrdersService_DeleteOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrder'
type OrdersService_DeleteOrder_Call struct {
	*mock.Call
}

// DeleteOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 uuid.UUID
func (_e *OrdersService_Expecter) DeleteOrder(ctx interface{}, _a1 interface{}) *OrdersService_DeleteOrder_Call {
	return &OrdersService_DeleteOrder_Call{Call: _e.mock.On("DeleteOrder", ctx, _a1)}
}

func (_c *OrdersService_DeleteOrder_Call) Run(run func(ctx context.Context, _a1 uuid.UUID)) *OrdersService_DeleteOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *OrdersService_DeleteOrder_Call) Return(_a0 error) *OrdersService_DeleteOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrdersService_DeleteOrder_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *OrdersService_DeleteOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: ctx, _a1
func (_m *OrdersService) GetOrder(ctx context.Context, _a1 uuid.UUID) (*model.Order, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Order, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Order); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrdersService_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type OrdersService_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 uuid.UUID
func (_e *OrdersService_Expecter) GetOrder(ctx interface{}, _a1 interface{}) *OrdersService_GetOrder_Call {
	return &OrdersService_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, _a1)}
}

func (_c *OrdersService_GetOrder_Call) Run(run func(ctx context.Context, _a1 uuid.UUID)) *OrdersService_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *OrdersService_GetOrder_Call) Return(_a0 *model.Order, _a1 error) *OrdersService_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrdersService_GetOrder_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Order, error)) *OrdersService_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserOrders provides a mock function with given fields: ctx, userUUID
func (_m *OrdersService) GetUserOrders(ctx context.Context, userUUID uuid.UUID) ([]model.Order, error) {
	ret := _m.Called(ctx, userUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserOrders")
	}

	var r0 []model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.Order, error)); ok {
		return rf(ctx, userUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.Order); ok {
		r0 = rf(ctx, userUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrdersService_GetUserOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserOrders'
type OrdersService_GetUserOrders_Call struct {
	*mock.Call
}

// GetUserOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID uuid.UUID
func (_e *OrdersService_Expecter) GetUserOrders(ctx interface{}, userUUID interface{}) *OrdersService_GetUserOrders_Call {
	return &OrdersService_GetUserOrders_Call{Call: _e.mock.On("GetUserOrders", ctx, userUUID)}
}

func (_c *OrdersService_GetUserOrders_Call) Run(run func(ctx context.Context, userUUID uuid.UUID)) *OrdersService_GetUserOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *OrdersService_GetUserOrders_Call) Return(_a0 []model.Order, _a1 error) *OrdersService_GetUserOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrdersService_GetUserOrders_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]model.Order, error)) *OrdersService_GetUserOrders_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrder provides a mock function with given fields: ctx, order
func (_m *OrdersService) UpdateOrder(ctx context.Context, order model.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrdersService_UpdateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrder'
type OrdersService_UpdateOrder_Call struct {
	*mock.Call
}

// UpdateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.Order
func (_e *OrdersService_Expecter) UpdateOrder(ctx interface{}, order interface{}) *OrdersService_UpdateOrder_Call {
	return &OrdersService_UpdateOrder_Call{Call: _e.mock.On("UpdateOrder", ctx, order)}
}

func (_c *OrdersService_UpdateOrder_Call) Run(run func(ctx context.Context, order model.Order)) *OrdersService_UpdateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Order))
	})
	return _c
}

func (_c *OrdersService_UpdateOrder_Call) Return(_a0 error) *OrdersService_UpdateOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrdersService_UpdateOrder_Call) RunAndReturn(run func(context.Context, model.Order) error) *OrdersService_UpdateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrdersService creates a new instance of OrdersService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrdersService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrdersService {
	mock := &OrdersService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
