services:
  # Раздел, описывающий контейнеры, которые требуются для работы Notification-сервиса
  notification-service:
    image: notification-service:1.0.0
    container_name: notification_service
    build:
      context: ../../..
      dockerfile: ./notification/Dockerfile
    env_file:
      - .env
    networks:
      rocketfactory-net:
        ipv4_address: 172.19.0.18

networks:
  # Сетевые настройки
  rocketfactory-net:
    external: true
    # Мы не создаём новую сеть, а подключаемся к уже существующей общей сети "rocketfactory-net"
    # Эта сеть создаётся один раз в docker-compose.yml или вручную через docker network create
