// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Producer is an autogenerated mock type for the Producer type
type Producer struct {
	mock.Mock
}

type Producer_Expecter struct {
	mock *mock.Mock
}

func (_m *Producer) EXPECT() *Producer_Expecter {
	return &Producer_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: ctx, key, value
func (_m *Producer) Send(ctx context.Context, key []byte, value []byte) error {
	ret := _m.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, []byte) error); ok {
		r0 = rf(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Producer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type Producer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - key []byte
//   - value []byte
func (_e *Producer_Expecter) Send(ctx interface{}, key interface{}, value interface{}) *Producer_Send_Call {
	return &Producer_Send_Call{Call: _e.mock.On("Send", ctx, key, value)}
}

func (_c *Producer_Send_Call) Run(run func(ctx context.Context, key []byte, value []byte)) *Producer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].([]byte))
	})
	return _c
}

func (_c *Producer_Send_Call) Return(_a0 error) *Producer_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Producer_Send_Call) RunAndReturn(run func(context.Context, []byte, []byte) error) *Producer_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewProducer creates a new instance of Producer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Producer {
	mock := &Producer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
