// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	sarama "github.com/IBM/sarama"
	mock "github.com/stretchr/testify/mock"
)

// OrderPaidEventConsumerConfig is an autogenerated mock type for the OrderPaidEventConsumerConfig type
type OrderPaidEventConsumerConfig struct {
	mock.Mock
}

type OrderPaidEventConsumerConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderPaidEventConsumerConfig) EXPECT() *OrderPaidEventConsumerConfig_Expecter {
	return &OrderPaidEventConsumerConfig_Expecter{mock: &_m.Mock}
}

// Config provides a mock function with no fields
func (_m *OrderPaidEventConsumerConfig) Config() *sarama.Config {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 *sarama.Config
	if rf, ok := ret.Get(0).(func() *sarama.Config); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sarama.Config)
		}
	}

	return r0
}

// OrderPaidEventConsumerConfig_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type OrderPaidEventConsumerConfig_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *OrderPaidEventConsumerConfig_Expecter) Config() *OrderPaidEventConsumerConfig_Config_Call {
	return &OrderPaidEventConsumerConfig_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *OrderPaidEventConsumerConfig_Config_Call) Run(run func()) *OrderPaidEventConsumerConfig_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderPaidEventConsumerConfig_Config_Call) Return(_a0 *sarama.Config) *OrderPaidEventConsumerConfig_Config_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderPaidEventConsumerConfig_Config_Call) RunAndReturn(run func() *sarama.Config) *OrderPaidEventConsumerConfig_Config_Call {
	_c.Call.Return(run)
	return _c
}

// GroupID provides a mock function with no fields
func (_m *OrderPaidEventConsumerConfig) GroupID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GroupID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// OrderPaidEventConsumerConfig_GroupID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GroupID'
type OrderPaidEventConsumerConfig_GroupID_Call struct {
	*mock.Call
}

// GroupID is a helper method to define mock.On call
func (_e *OrderPaidEventConsumerConfig_Expecter) GroupID() *OrderPaidEventConsumerConfig_GroupID_Call {
	return &OrderPaidEventConsumerConfig_GroupID_Call{Call: _e.mock.On("GroupID")}
}

func (_c *OrderPaidEventConsumerConfig_GroupID_Call) Run(run func()) *OrderPaidEventConsumerConfig_GroupID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderPaidEventConsumerConfig_GroupID_Call) Return(_a0 string) *OrderPaidEventConsumerConfig_GroupID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderPaidEventConsumerConfig_GroupID_Call) RunAndReturn(run func() string) *OrderPaidEventConsumerConfig_GroupID_Call {
	_c.Call.Return(run)
	return _c
}

// Topic provides a mock function with no fields
func (_m *OrderPaidEventConsumerConfig) Topic() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Topic")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// OrderPaidEventConsumerConfig_Topic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Topic'
type OrderPaidEventConsumerConfig_Topic_Call struct {
	*mock.Call
}

// Topic is a helper method to define mock.On call
func (_e *OrderPaidEventConsumerConfig_Expecter) Topic() *OrderPaidEventConsumerConfig_Topic_Call {
	return &OrderPaidEventConsumerConfig_Topic_Call{Call: _e.mock.On("Topic")}
}

func (_c *OrderPaidEventConsumerConfig_Topic_Call) Run(run func()) *OrderPaidEventConsumerConfig_Topic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderPaidEventConsumerConfig_Topic_Call) Return(_a0 string) *OrderPaidEventConsumerConfig_Topic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderPaidEventConsumerConfig_Topic_Call) RunAndReturn(run func() string) *OrderPaidEventConsumerConfig_Topic_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderPaidEventConsumerConfig creates a new instance of OrderPaidEventConsumerConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderPaidEventConsumerConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderPaidEventConsumerConfig {
	mock := &OrderPaidEventConsumerConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
