// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "github.com/andredubov/rocket-factory/assembly/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// OrderPaidEventDecoder is an autogenerated mock type for the OrderPaidEventDecoder type
type OrderPaidEventDecoder struct {
	mock.Mock
}

type OrderPaidEventDecoder_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderPaidEventDecoder) EXPECT() *OrderPaidEventDecoder_Expecter {
	return &OrderPaidEventDecoder_Expecter{mock: &_m.Mock}
}

// Decode provides a mock function with given fields: data
func (_m *OrderPaidEventDecoder) Decode(data []byte) (model.OrderPaidEvent, error) {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 model.OrderPaidEvent
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (model.OrderPaidEvent, error)); ok {
		return rf(data)
	}
	if rf, ok := ret.Get(0).(func([]byte) model.OrderPaidEvent); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Get(0).(model.OrderPaidEvent)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderPaidEventDecoder_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type OrderPaidEventDecoder_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - data []byte
func (_e *OrderPaidEventDecoder_Expecter) Decode(data interface{}) *OrderPaidEventDecoder_Decode_Call {
	return &OrderPaidEventDecoder_Decode_Call{Call: _e.mock.On("Decode", data)}
}

func (_c *OrderPaidEventDecoder_Decode_Call) Run(run func(data []byte)) *OrderPaidEventDecoder_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *OrderPaidEventDecoder_Decode_Call) Return(_a0 model.OrderPaidEvent, _a1 error) *OrderPaidEventDecoder_Decode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderPaidEventDecoder_Decode_Call) RunAndReturn(run func([]byte) (model.OrderPaidEvent, error)) *OrderPaidEventDecoder_Decode_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderPaidEventDecoder creates a new instance of OrderPaidEventDecoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderPaidEventDecoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderPaidEventDecoder {
	mock := &OrderPaidEventDecoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
