services:
  # Раздел, описывающий контейнеры, которые требуются для работы Order-сервиса
  order-service:
    image: order-service:1.0.0
    container_name: order_service
    build:
      context: ../../..
      dockerfile: ./order/Dockerfile
    env_file:
      - .env
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    depends_on:
      order-postgres:
        condition: service_healthy
    networks:
      rocketfactory-net:
        ipv4_address: 172.19.0.7

  order-postgres:
    # Контейнер с PostgreSQL, используемый для хранения данных заказов
    image: ${PG_IMAGE_NAME}
    # Используем официальный образ PostgreSQL версии 17 на базе Alpine Linux
    # Это лёгкая и быстрая сборка, которая экономит ресурсы
    container_name: order_postgres
    environment:
      # Переменные окружения, используемые при запуске контейнера
      POSTGRES_DB: ${PG_DB} # Имя базы данных, которая будет создана при запуске
      POSTGRES_USER: ${PG_USER} # Имя пользователя, создаваемого в базе
      POSTGRES_PASSWORD: ${PG_PASSWORD} # Пароль для указанного пользователя
    volumes:
      - order_postgres_volume:/var/lib/postgresql/data
      # Определяем том, который будет использоваться для хранения данных PostgreSQL
      # Он сохраняет данные между перезапусками контейнера
    ports:
      - "${EXTERNAL_PG_PORT}:${INTERNAL_PG_PORT}"
      # Пробрасываем внутренний порт PostgreSQL (${PG_PORT}) на порт хоста (${PG_PORT_OUT})
      # Это нужно, чтобы другие сервисы или инструменты могли подключиться к базе
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}" ]
      # Настраиваем проверку готовности контейнера — pg_isready проверяет, принимает ли база подключения
      interval: 10s # Интервал между проверками — каждые 10 секунд
      timeout: 5s # Время ожидания ответа от проверки
      retries: 5 # После 5 неудачных попыток подряд контейнер считается "unhealthy"
    restart: unless-stopped
    # Автоматически перезапускаем контейнер, если он аварийно завершился
    # Если контейнер был остановлен вручную — не перезапускаем
    networks:
      rocketfactory-net:
        ipv4_address: 172.19.0.8
      # Подключаемся к общей сети, чтобы другие микросервисы (например, Order-сервис) могли найти этот контейнер по имени "postgres-order"

volumes:
  # Раздел с томами — определяем, какие дисковые ресурсы создаёт и использует Docker
  order_postgres_volume:
    name: order_postgres_volume
    # Именованный том для хранения данных Order-сервиса в PostgreSQL
    # Позволяет сохранять состояние базы даже после перезапуска контейнера

networks:
  # Сетевые настройки
  rocketfactory-net:
    external: true
    # Мы не создаём новую сеть, а подключаемся к уже существующей общей сети "rocketfactory-net"
    # Эта сеть создаётся один раз в docker-compose.yml или вручную через docker network create
