// Code generated by ogen, DO NOT EDIT.

package order_v1

// setDefaults set default value of fields.
func (s *BadRequestError) setDefaults() {
	{
		val := int(400)
		s.Code = val
	}
	{
		val := string("Bad Request")
		s.Message = val
	}
}

// setDefaults set default value of fields.
func (s *ConflictError) setDefaults() {
	{
		val := int(409)
		s.Code = val
	}
	{
		val := string("Conflict")
		s.Message = val
	}
}

// setDefaults set default value of fields.
func (s *GenericError) setDefaults() {
	{
		val := int(500)
		s.Code.SetTo(val)
	}
	{
		val := string("Something went wrong")
		s.Message.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *InternalServerError) setDefaults() {
	{
		val := int(500)
		s.Code = val
	}
	{
		val := string("Internal Server Error")
		s.Message = val
	}
}

// setDefaults set default value of fields.
func (s *NotFoundError) setDefaults() {
	{
		val := int(404)
		s.Code = val
	}
	{
		val := string("Not Found")
		s.Message = val
	}
}
