// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	bson "go.mongodb.org/mongo-driver/bson"

	mock "github.com/stretchr/testify/mock"
)

// MongoCursor is an autogenerated mock type for the MongoCursor type
type MongoCursor struct {
	mock.Mock
}

type MongoCursor_Expecter struct {
	mock *mock.Mock
}

func (_m *MongoCursor) EXPECT() *MongoCursor_Expecter {
	return &MongoCursor_Expecter{mock: &_m.Mock}
}

// All provides a mock function with given fields: ctx, results
func (_m *MongoCursor) All(ctx context.Context, results interface{}) error {
	ret := _m.Called(ctx, results)

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, results)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MongoCursor_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type MongoCursor_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
//   - ctx context.Context
//   - results interface{}
func (_e *MongoCursor_Expecter) All(ctx interface{}, results interface{}) *MongoCursor_All_Call {
	return &MongoCursor_All_Call{Call: _e.mock.On("All", ctx, results)}
}

func (_c *MongoCursor_All_Call) Run(run func(ctx context.Context, results interface{})) *MongoCursor_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *MongoCursor_All_Call) Return(_a0 error) *MongoCursor_All_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MongoCursor_All_Call) RunAndReturn(run func(context.Context, interface{}) error) *MongoCursor_All_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with given fields: ctx
func (_m *MongoCursor) Close(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MongoCursor_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MongoCursor_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MongoCursor_Expecter) Close(ctx interface{}) *MongoCursor_Close_Call {
	return &MongoCursor_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MongoCursor_Close_Call) Run(run func(ctx context.Context)) *MongoCursor_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MongoCursor_Close_Call) Return(_a0 error) *MongoCursor_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MongoCursor_Close_Call) RunAndReturn(run func(context.Context) error) *MongoCursor_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Current provides a mock function with no fields
func (_m *MongoCursor) Current() bson.Raw {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Current")
	}

	var r0 bson.Raw
	if rf, ok := ret.Get(0).(func() bson.Raw); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bson.Raw)
		}
	}

	return r0
}

// MongoCursor_Current_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Current'
type MongoCursor_Current_Call struct {
	*mock.Call
}

// Current is a helper method to define mock.On call
func (_e *MongoCursor_Expecter) Current() *MongoCursor_Current_Call {
	return &MongoCursor_Current_Call{Call: _e.mock.On("Current")}
}

func (_c *MongoCursor_Current_Call) Run(run func()) *MongoCursor_Current_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MongoCursor_Current_Call) Return(_a0 bson.Raw) *MongoCursor_Current_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MongoCursor_Current_Call) RunAndReturn(run func() bson.Raw) *MongoCursor_Current_Call {
	_c.Call.Return(run)
	return _c
}

// Decode provides a mock function with given fields: val
func (_m *MongoCursor) Decode(val interface{}) error {
	ret := _m.Called(val)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(val)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MongoCursor_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type MongoCursor_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - val interface{}
func (_e *MongoCursor_Expecter) Decode(val interface{}) *MongoCursor_Decode_Call {
	return &MongoCursor_Decode_Call{Call: _e.mock.On("Decode", val)}
}

func (_c *MongoCursor_Decode_Call) Run(run func(val interface{})) *MongoCursor_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MongoCursor_Decode_Call) Return(_a0 error) *MongoCursor_Decode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MongoCursor_Decode_Call) RunAndReturn(run func(interface{}) error) *MongoCursor_Decode_Call {
	_c.Call.Return(run)
	return _c
}

// Err provides a mock function with no fields
func (_m *MongoCursor) Err() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Err")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MongoCursor_Err_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Err'
type MongoCursor_Err_Call struct {
	*mock.Call
}

// Err is a helper method to define mock.On call
func (_e *MongoCursor_Expecter) Err() *MongoCursor_Err_Call {
	return &MongoCursor_Err_Call{Call: _e.mock.On("Err")}
}

func (_c *MongoCursor_Err_Call) Run(run func()) *MongoCursor_Err_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MongoCursor_Err_Call) Return(_a0 error) *MongoCursor_Err_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MongoCursor_Err_Call) RunAndReturn(run func() error) *MongoCursor_Err_Call {
	_c.Call.Return(run)
	return _c
}

// GetBatchSize provides a mock function with no fields
func (_m *MongoCursor) GetBatchSize() int32 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBatchSize")
	}

	var r0 int32
	if rf, ok := ret.Get(0).(func() int32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int32)
	}

	return r0
}

// MongoCursor_GetBatchSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBatchSize'
type MongoCursor_GetBatchSize_Call struct {
	*mock.Call
}

// GetBatchSize is a helper method to define mock.On call
func (_e *MongoCursor_Expecter) GetBatchSize() *MongoCursor_GetBatchSize_Call {
	return &MongoCursor_GetBatchSize_Call{Call: _e.mock.On("GetBatchSize")}
}

func (_c *MongoCursor_GetBatchSize_Call) Run(run func()) *MongoCursor_GetBatchSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MongoCursor_GetBatchSize_Call) Return(_a0 int32) *MongoCursor_GetBatchSize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MongoCursor_GetBatchSize_Call) RunAndReturn(run func() int32) *MongoCursor_GetBatchSize_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function with no fields
func (_m *MongoCursor) ID() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// MongoCursor_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MongoCursor_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MongoCursor_Expecter) ID() *MongoCursor_ID_Call {
	return &MongoCursor_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MongoCursor_ID_Call) Run(run func()) *MongoCursor_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MongoCursor_ID_Call) Return(_a0 int64) *MongoCursor_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MongoCursor_ID_Call) RunAndReturn(run func() int64) *MongoCursor_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Next provides a mock function with given fields: ctx
func (_m *MongoCursor) Next(ctx context.Context) bool {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MongoCursor_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type MongoCursor_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MongoCursor_Expecter) Next(ctx interface{}) *MongoCursor_Next_Call {
	return &MongoCursor_Next_Call{Call: _e.mock.On("Next", ctx)}
}

func (_c *MongoCursor_Next_Call) Run(run func(ctx context.Context)) *MongoCursor_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MongoCursor_Next_Call) Return(_a0 bool) *MongoCursor_Next_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MongoCursor_Next_Call) RunAndReturn(run func(context.Context) bool) *MongoCursor_Next_Call {
	_c.Call.Return(run)
	return _c
}

// RemainingBatchLength provides a mock function with no fields
func (_m *MongoCursor) RemainingBatchLength() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RemainingBatchLength")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MongoCursor_RemainingBatchLength_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemainingBatchLength'
type MongoCursor_RemainingBatchLength_Call struct {
	*mock.Call
}

// RemainingBatchLength is a helper method to define mock.On call
func (_e *MongoCursor_Expecter) RemainingBatchLength() *MongoCursor_RemainingBatchLength_Call {
	return &MongoCursor_RemainingBatchLength_Call{Call: _e.mock.On("RemainingBatchLength")}
}

func (_c *MongoCursor_RemainingBatchLength_Call) Run(run func()) *MongoCursor_RemainingBatchLength_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MongoCursor_RemainingBatchLength_Call) Return(_a0 int) *MongoCursor_RemainingBatchLength_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MongoCursor_RemainingBatchLength_Call) RunAndReturn(run func() int) *MongoCursor_RemainingBatchLength_Call {
	_c.Call.Return(run)
	return _c
}

// SetBatchSize provides a mock function with given fields: _a0
func (_m *MongoCursor) SetBatchSize(_a0 int32) {
	_m.Called(_a0)
}

// MongoCursor_SetBatchSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBatchSize'
type MongoCursor_SetBatchSize_Call struct {
	*mock.Call
}

// SetBatchSize is a helper method to define mock.On call
//   - _a0 int32
func (_e *MongoCursor_Expecter) SetBatchSize(_a0 interface{}) *MongoCursor_SetBatchSize_Call {
	return &MongoCursor_SetBatchSize_Call{Call: _e.mock.On("SetBatchSize", _a0)}
}

func (_c *MongoCursor_SetBatchSize_Call) Run(run func(_a0 int32)) *MongoCursor_SetBatchSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int32))
	})
	return _c
}

func (_c *MongoCursor_SetBatchSize_Call) Return() *MongoCursor_SetBatchSize_Call {
	_c.Call.Return()
	return _c
}

func (_c *MongoCursor_SetBatchSize_Call) RunAndReturn(run func(int32)) *MongoCursor_SetBatchSize_Call {
	_c.Run(run)
	return _c
}

// TryNext provides a mock function with given fields: ctx
func (_m *MongoCursor) TryNext(ctx context.Context) bool {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TryNext")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MongoCursor_TryNext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TryNext'
type MongoCursor_TryNext_Call struct {
	*mock.Call
}

// TryNext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MongoCursor_Expecter) TryNext(ctx interface{}) *MongoCursor_TryNext_Call {
	return &MongoCursor_TryNext_Call{Call: _e.mock.On("TryNext", ctx)}
}

func (_c *MongoCursor_TryNext_Call) Run(run func(ctx context.Context)) *MongoCursor_TryNext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MongoCursor_TryNext_Call) Return(_a0 bool) *MongoCursor_TryNext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MongoCursor_TryNext_Call) RunAndReturn(run func(context.Context) bool) *MongoCursor_TryNext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMongoCursor creates a new instance of MongoCursor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMongoCursor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MongoCursor {
	mock := &MongoCursor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
