services:
  # Здесь описываются контейнеры, необходимые для Payment-сервиса
  payment-service:
    image: payment-service:1.0.0
    container_name: payment_service
    build:
      context: ../../..
      dockerfile: ./deploy/docker/payment/Dockerfile
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "grpc-health-probe", "-addr=localhost:50052" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      rocketfactory-net:
        ipv4_address: 172.19.0.21

networks:
  # Сетевые настройки
  rocketfactory-net:
    external: true
